version: "3.7"
services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/url_shortener

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/url_shortener

  postgres:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    volumes:
      - ./createTestDB.sh:/docker-entrypoint-initdb.d/createTestDB.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=url_shortener
